name: fuksiarz
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.17
  intl: any
  go_router: ^14.7.2
  flutter_bloc: ^9.0.0
  injectable: ^2.5.0
  get_it: ^8.0.3
  rxdart: ^0.28.0
  fpdart: ^1.1.1
  freezed_annotation: ^2.4.4
  dio: ^5.8.0
  retrofit: ^4.4.0
  responsive_builder: ^0.7.1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.5.8
  build_runner: ^2.1.11
  json_serializable: ^6.3.1
  injectable_generator: ^2.7.0
  bloc_test: ^10.0.0
  mocktail: ^1.0.4
  flutter_lints: ^5.0.0
  retrofit_generator: ^9.1.7
  patrol: ^3.14.1
  patrol_cli: ^3.5.1
  integration_test:
    sdk: flutter
  patrol_finders: ^2.7.0

dependency_overrides:
  test_api: 0.7.4

patrol:
  app_name: Fuksiarz
  android:
    package_name: com.example.fuksiarz

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
